--- #YAML:1.0
distribution_type:     module
name:                  Net-Wire10
license:               perl
version:               1.03
build_requires:
	Test:               0.0
requires:
	Digest::SHA1:       0.0
	Encode:             0.0
	Exporter:           0.0
	IO::Select:         0.0
	IO::Socket:         0.0
	threads:            0.0
	threads::shared:    0.0
	utf8:               0.0
meta-spec:
	url:                http://module-build.sourceforge.net/META-spec-v1.4.html
	version:            1.4
