--- #YAML:1.0
name:                Net-Wire10
version:             1.00
distribution_type:   module
requires:     
    Digest::SHA1:                  0
    Encode:                        0
    IO::Select:                    0
    IO::Socket:                    0
    threads:                       0
    threads::shared:               0
    utf8:                          0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
